### ISSUE TITLE
Font Sizing Inconsistent

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#49]
Hello! I am unsure if this is a bug or a misconfiguration in my settings. As seen in the screenshot below, the text outside of the table is significantly smaller than the text in the table. My font size settings are as follows:

Remoods Theme > Markdown Editor & Render Viewer - Base Font Size (px) > 30
Remoods Theme > Markdown Editor & Render Viewer - Monospace Font Size (px) > 30

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/09c2526e-eb88-406e-a257-6ace6342797f)

Also, strangely, the WYSIWYG editor does not reflect any of the font size adjustments:

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/e3fa34bd-bf9a-467c-9e49-b0f4afbfd353)

**Comment by Sinacs** [comment]
Hi @ScriptInfra, I've set the font size to both `30` and the font size settings are working fine. But it is rare to set that large sizing and will create a visual problem on ordered list token:

In Markdown Editor:

![Screenshot 2023-05-27 134119](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/3f260132-0ae7-4c02-9df6-8dd735e1eb66)

In WYSIWYG Editor:

![Screenshot 2023-05-27 134004](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/e80fdca4-9db8-4c75-baea-6a4df934bae8)

So, please make sure you didn't have any other plugins which limiting your text sizing, or without any text sizing custom styles in your custom CSS.

---

Additionally, below are two tips that related to your questions:

1. About `Base Font Size` and `Monospace Font Size`

The scale of `Base Font Size` and `Monospace Font Size` are not consistent even if it has set to the same font size, it was because the font size completely depends on the font you use.

2. About the WYSIWYG editor.

The `Monospace Font Size` is only related to `Monospace Font`. To explain in other way, it is related to only Markdown Syntax, inline code and code block. So, the table in WYSIWYG editor is not in the Monospace font group.

**Comment by ScriptInfra** [comment]
Thanks so much! The issue was related to my userstyle.css and userchrome.css. After removing the custom entries, I am now able to tweak the font as needed. Thanks for the great explanation on the font sizes, that is very helpful as well!
