### ISSUE TITLE
Highlighting code blocks in the markdown view has no background

### ISSUE THREAD

**Issue by zakeryooo** [Sinacs/Joplin.Plugin.ReMoods.Theme#60]
## Environment:

 - OS: Windows 11
 - Joplin version: 2.11.11
 - ReMoods theme version: 4.6.0

## Describe the bug:
Using the dark theme if I highlight text inside a code block in the markdown editor there's no visual indication as to what has been highlighted. 

## To Reproduce:
Set theme to dark
Add a code block 
```
<?php 
print 'oh';
?>
```
Highlight print 'oh', no colour indication shows what is selected.

## Expected behavior:
There's a background colour

**Comment by Sinacs** [comment]
Hi @zakeryooo! Is this issue only appeared after update to v4.6.0?

**Comment by zakeryooo** [comment]
Sorry, I'm not sure, I've only used v4.6.0, today is my first day using the plugin (which I love btw, just this issue I'm having).

**Comment by Sinacs** [comment]
Ok! Thank you for the reply! I think the problem is due to you didn't install the Rich Markdown plugin. Please feel free to read about the ReMoods theme getting started guide: https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/blob/master/Doc-GettingStartedGuide.md#install-and-configure-3-important-plugins

Just let me know if it still does not work for you.

-Sinacs

**Comment by zakeryooo** [comment]
Ah, my mistake, sorry about that! Somehow missed the bit about needing to install the Rich Markdown plugin, installed it and all good now. Thanks!

**Comment by Sinacs** [comment]
That's great! Thanks for supporting ReMoods theme! 🥂
